name: asmt

container:
  - base:

      - docker.qe.aerospike.com/build/aerospike-server:arm-centos-7
      - docker.qe.aerospike.com/build/aerospike-server:arm-rhel-8
      - docker.qe.aerospike.com/build/aerospike-server:arm-rhel-9
      - docker.qe.aerospike.com/build/aerospike-server:arm-debian-11
      - docker.qe.aerospike.com/build/aerospike-server:arm-ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-server:arm-ubuntu-22.04

      - docker.qe.aerospike.com/build/aerospike-server:x86-centos-7
      - docker.qe.aerospike.com/build/aerospike-server:x86-rhel-8
      - docker.qe.aerospike.com/build/aerospike-server:x86-rhel-9
      - docker.qe.aerospike.com/build/aerospike-server:x86-debian-10
      - docker.qe.aerospike.com/build/aerospike-server:x86-debian-11
      - docker.qe.aerospike.com/build/aerospike-server:x86-ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-server:x86-ubuntu-22.04

build:
  - name: default
    script:
      - make
      - make $PKG
    artifact:
      - target/bin/*
      - target/packages/*
